name: Publish

run-name: "Publish (site_mode: ${{github.event.inputs.site_mode}})"

on:
  workflow_dispatch:
    inputs:
      site_mode:
        description: Site mode
        required: true
        default: testing
        type: choice
        options:
        #- development
        - testing
        - production
      chinese:
        description: 'Build chinese?'
        required: true
        default: false
        type: boolean

env:
  CN: ${{github.event.inputs.chinese}}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Build Packages
      run: |
        SUB_PARAMETERS="-- --locale en"

        [[ "$CN" == "true" ]] && SUB_PARAMETERS="$SUB_PARAMETERS --locale zh-CN"

        NODE_OPTIONS="--max-old-space-size=12288" npm run build ${SUB_PARAMETERS}
    
    - name: Configure AWS Credentials
      env:
        mode: ${{github.event.inputs.site_mode}}
        AWS_ACCESS_KEY_PROD: ${{secrets.AWS_ACCESS_KEY_PROD}}
        AWS_SECRET_KEY_PROD: ${{secrets.AWS_SECRET_KEY_PROD}}
        AWS_DISTRIBUTION_ID_PROD: ${{secrets.AWS_DISTRIBUTION_ID_PROD}}
        AWS_ACCESS_KEY_TEST: ${{secrets.AWS_ACCESS_KEY_TEST}}
        AWS_SECRET_KEY_TEST: ${{secrets.AWS_SECRET_KEY_TEST}}
        AWS_DISTRIBUTION_ID_TEST: ${{secrets.AWS_DISTRIBUTION_ID_TEST}}
      run: |
        if [ "${mode}" = "production" ]; then
          echo "AWS_BUCKET_URL=s3://api2static.onlyoffice.com" >> "$GITHUB_ENV"
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_PROD}" >> "$GITHUB_ENV"
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY_PROD}" >> "$GITHUB_ENV"
          echo "AWS_REGION=us-west-2" >> "$GITHUB_ENV"
          echo "AWS_DISTRIBUTION_ID=${AWS_DISTRIBUTION_ID_PROD}" >> "$GITHUB_ENV"
        elif [ "${mode}" = "testing" ]; then
          echo "AWS_BUCKET_URL=s3://api2static.teamlab.info" >> "$GITHUB_ENV"
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_TEST}" >> "$GITHUB_ENV"
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY_TEST}" >> "$GITHUB_ENV"
          echo "AWS_DISTRIBUTION_ID=${AWS_DISTRIBUTION_ID_TEST}" >> "$GITHUB_ENV"
          echo "AWS_REGION=us-east-1" >> "$GITHUB_ENV"
        elif [ "${mode}" = "development" ]; then
          echo "Development bucket dose not exist"
          exit 1
        else
          echo "Invalid site mode: $m"
          exit 1
        fi

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{env.AWS_REGION}}

    - name: Sync AWS Bucket
      working-directory: build
      run: |
          #!/bin/bash

          # Define all possible languages
          # EN all time build by default and not specifyed in this array
          ALL_LANGS=("zh-CN")

          # Languages that were actually built
          BUILT_LANGS=("en")  # Modify this dynamically

          [[ "$CN" == "true" ]] && BUILT_LANGS+="zh-CN"

          # Generate exclusion flags
          EXCLUDE_FLAGS=()
          for lang in "${ALL_LANGS[@]}"; do
             if [[ ! " ${BUILT_LANGS[@]} " =~ " ${lang} " ]]; then
               EXCLUDE_FLAGS+=("--exclude \"${lang}/*\"")
             fi
          done

          # Convert array to string
          EXCLUDE_STR=$(IFS=" " ; echo "${EXCLUDE_FLAGS[*]}")

          # Execute the sync command
          eval "aws s3 sync . ${{env.AWS_BUCKET_URL}} --delete $EXCLUDE_STR"

    - name: Invalidate AWS CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{env.AWS_DISTRIBUTION_ID}} --paths '/*'
